### ISSUE TITLE
[feature] colored JSX

### ISSUE THREAD

**Issue by kiruushaaa** [eenaree/webstorm-new-ui-theme#11]
Hi! I guess this might be useful. I've taken default color from WebStorm. Didn't test in `.jsx` actually

<img width="598" alt="image" src="https://github.com/eenaree/webstorm-new-ui-theme/assets/18754878/78b3daf0-0be9-4ecc-82ef-ad5faf41a1b0">

```json
"editor.tokenColorCustomizations": {
        "[Webstorm New Light]": {
            "textMateRules": [
                {
                    "scope": "support.class.component.tsx",
                    "settings": {
                        "foreground": "#ad6339",
                    }
                },
                {
                    "scope": "support.class.component.jsx",
                    "settings": {
                        "foreground": "#ad6339",
                    }
                },
            ]
        },
    },
```

**Comment by eenaree** [comment]
A few month ago, WebStorm supported [syntax highlighting for React server and client component](https://blog.jetbrains.com/webstorm/2024/01/webstorm-2023-3-3/).

![WS233_EAP_Digest3_RSC](https://github.com/eenaree/webstorm-new-ui-theme/assets/37580351/df1f74eb-7083-453b-a574-b9f664729881)

But... In VSCode, not support.

Currently, the syntax highlighting for components applied only in the dark theme.
The problem is, the color is server component color. I used that color because I see it in many examples.

Based on WebStorm, Since VSCode doesn't differentiate between components, it seems that the color of base component should be the color of the client component. 

What do you think? I'm not sure If I should apply this color.

**Comment by kiruushaaa** [comment]
Oh, didn’t even notice 😁

Actually can’t suggest anything, since it’s turned out to be personal. I just wanted different colors for Components and native html tags so sent you that.

So my main “I want” is just a visual difference.

**Comment by eenaree** [comment]
ok. I will make difference in the Light theme first.
color is... likely to be what we saw earlier. orange?

**Comment by kiruushaaa** [comment]
Yep. `#AD6339`
<img width="1094" alt="image" src="https://github.com/eenaree/webstorm-new-ui-theme/assets/18754878/16e2873f-ae78-498c-97a2-eb7096ed6d20">

Also I didn't manage to see server components painted with other color.

upd. It's okay, I was trying to import the server one into the client 🫠

**Comment by eenaree** [comment]
Thanks for letting me know the color. 
I applied what you wanted. New version 2.7.0 is coming soon!
